# Given string s and string t, that is generated by randomly shuffling s and adding one more letter, find what letter was added

from collections import Counter


class FindDifference:
    def findDifference(self, s, t):
        bagS, bagT = Counter(s), Counter(t)

        diffBag = {k: v for k, v in bagT.items() if bagS[k] != bagT[k]}

        return list(diffBag.keys())[0]


print(FindDifference().findDifference('abcd', 'abcde'))
